---
name: Terraform - Cloudflare

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-cloudflare.yml
      - terraform/cloudflare/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-cloudflare.yml
      - terraform/cloudflare/**

permissions: read-all

jobs:
  cloudflare:
    name: Cloudflare
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/cloudflare
      cloud-provider: google
      google-workload-identity-pool: projects/800000204119/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      google-service-account: github-actions@woffenden.iam.gserviceaccount.com
