---
name: Terraform - Google - Woffenden - MTA-STS

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-google-woffenden-mta-sts.yml
      - terraform/google/woffenden/mta-sts/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-google-woffenden-mta-sts.yml
      - terraform/google/woffenden/mta-sts/**

permissions: read-all

jobs:
  mta-sts:
    name: MTA-STS
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/google/woffenden/mta-sts
      cloud-provider: google
      google-workload-identity-pool: projects/800000204119/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      google-service-account: github-actions@woffenden.iam.gserviceaccount.com
