---
  # TODO - Run scripts idempotently...

####################################################################################################
  
  - name: Check for UDM Boot Package
    ansible.builtin.stat:
      path: /mnt/data/unifi-os/dpkg-cache/stretch/packages/udm-boot_1.0.5_all.deb
    register: stat_udm_boot_pkg

  - name: Install UDM Boot Package
    ansible.builtin.shell: |
      curl -fsL "https://raw.githubusercontent.com/boostchicken-dev/udm-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh
    when: stat_udm_boot_pkg.stat.exists == false

####################################################################################################

  - name: Install Container Common Script
    ansible.builtin.template:
      src: mnt/data/on_boot.d/05-container-common.sh.j2
      dest: /mnt/data/on_boot.d/05-container-common.sh
      mode: '0700'
    register: create_container_common_script

  - name: Run Container Common Script
    ansible.builtin.shell: |
      /bin/sh /mnt/data/on_boot.d/05-container-common.sh
    when: create_container_common_script.changed

####################################################################################################

  - name: Install DNS Script
    ansible.builtin.template:
      src: mnt/data/on_boot.d/10-dns.sh.j2
      dest: /mnt/data/on_boot.d/10-dns.sh
      mode: '0700'

  - name: Install DNS Configuration
    ansible.builtin.template:
      src: mnt/data/podman/cni/20-dns.conflist.j2
      dest: /mnt/data/podman/cni/20-dns.conflist
      mode: '0644'

  - name: Install Cloudflare Teams DNS Script
    ansible.builtin.template:
      src: mnt/data/on_boot.d/99-cloudflare-teams-dns.sh.j2
      dest: /mnt/data/on_boot.d/99-cloudflare-teams-dns.sh
      mode: '0700'

  - name: Install Cloudflare Teams Tunnel Script
    ansible.builtin.template:
      src: mnt/data/on_boot.d/99-cloudflare-teams-tunnel.sh.j2
      dest: /mnt/data/on_boot.d/99-cloudflare-teams-tunnel.sh
      mode: '0700'
