---
collections:
  # https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.3.0
    source: https://galaxy.ansible.com

  # https://galaxy.ansible.com/community/general
  - name: community.general
    version: 4.6.1
    source: https://galaxy.ansible.com

  # https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 2.3.0
    source: https://galaxy.ansible.com
