FROM public.ecr.aws/docker/library/alpine:3.18.4 as BUILD

ARG AWS_SSO_SYNC_VERSION="2.0.3"

RUN apk add --no-cache \
      curl==8.4.0-r0 \
    && curl --location "https://github.com/awslabs/ssosync/releases/download/v${AWS_SSO_SYNC_VERSION}/ssosync_Linux_x86_64.tar.gz" \
         --output ssosync_Linux_arm64.tar.gz \
    && tar -xzf ssosync_Linux_arm64.tar.gz

FROM public.ecr.aws/lambda/provided:al2

COPY --from=BUILD /ssosync /usr/local/bin/ssosync
COPY src/var/runtime/bootstrap ${LAMBDA_RUNTIME_DIR}
COPY src/var/task/function.sh ${LAMBDA_TASK_ROOT}

RUN chmod 755 ${LAMBDA_RUNTIME_DIR}/bootstrap \
    && chmod 755 ${LAMBDA_TASK_ROOT}/function.sh

CMD ["function.handler"]
