#!/usr/bin/env bash

DEPENDABOT_CONFIGURATION_FILE=".github/dependabot.yml"

echo "Generating ${DEPENDABOT_CONFIGURATION_FILE}"
cat >"${DEPENDABOT_CONFIGURATION_FILE}" <<EOL
---
# This file is auto-generated by running the below command, do not manually amend.
# bash scripts/dependabot/configuration-generator.sh

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "jacobwoffenden"
EOL

for ecosystem in docker pip terraform; do

  echo "=== Ecosystem: ${ecosystem} ==="

  case ${ecosystem} in
  docker)
    SEARCH_PATTERN="*Dockerfile*"
    SKIP_FILE=".dependabot-docker-ignore"
    ;;
  pip)
    SEARCH_PATTERN="*requirements*.txt"
    SKIP_FILE=".dependabot-pip-ignore"
    ;;
  terraform)
    SEARCH_PATTERN=".terraform.lock.hcl"
    SKIP_FILE=".dependabot-terraform-ignore"
    ;;
  esac

  folders=$(find . -type f -name "${SEARCH_PATTERN}" -exec dirname {} \; | sort -h | uniq | cut -c 3-)
  export folders

  echo "=== Folders ==="
  echo "${folders}"

  for folder in ${folders}; do

    if [[ -f "${folder}/${SKIP_FILE}" ]]; then
      echo "Ignoring ${folder}"
      continue
    fi

    {
      printf "  - package-ecosystem: \"%s\"\n" "${ecosystem}"
      printf "    directory: \"%s\"\n" "${folder}"
      printf "    schedule:\n"
      printf "      interval: \"daily\"\n"
      printf "      time: \"09:00\"\n"
      printf "      timezone: \"Europe/London\"\n"
      printf "    commit-message:\n"
      printf "      prefix: \"📌 %s\"\n" "${ecosystem}"
      printf "      include: \"scope\"\n"
      printf "    reviewers:\n"
      printf "      - \"jacobwoffenden\"\n"
    } >>"${DEPENDABOT_CONFIGURATION_FILE}"

  done

done
