# hadolint global ignore=DL3008,DL3013

FROM mcr.microsoft.com/devcontainers/base:ubuntu

COPY .devcontainer/features/src/base/src/usr/local/bin/devcontainer-utils /usr/local/bin/devcontainer-utils

RUN apt-get update \
    && apt-get install --yes \
         python3-pip \
    && pip3 install --no-cache-dir --upgrade pip \
    && install --directory --owner=vscode --group=vscode /home/vscode/.devcontainer/feature-completion
