---
name: aws-production

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.1.9
  TERRAGRUNT_VERSION: v0.37.1

jobs:
  iam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terragrunt Deployment
        uses: woffenden/github-actions/standard-terragrunt-deployment@alpha
        with:
          working_directory: terraform/aws/accounts/production/iam
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}
