---
name: aws-root

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.1.8
  TERRAGRUNT_VERSION: v0.36.7

jobs:
  organisation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/aws/accounts/root/organisation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terragrunt Deployment
        uses: woffenden/github-actions/standard-terragrunt-deployment@alpha
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

  iam:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/aws/accounts/root/iam
    needs: organisation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terragrunt Deployment
        uses: woffenden/github-actions/standard-terragrunt-deployment@alpha
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}
