---
name: cloudflare

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
  TERRAFORM_VERSION: 1.2.9

jobs:
  cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Terraform Deployment
        uses: woffenden/github-actions/standard-terraform-deployment@alpha
        with:
          working_directory: terraform/cloudflare
          terraform_version: ${{ env.TERRAFORM_VERSION }}
