---
name: "cloudflare"

on:
  push:
    branches:
      - 'develop'

env:
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Install Terraform
        uses: woffenden/github-actions/install-terraform@alpha
        with:
          terraform_version: 1.1.7

      - name: Install Terragrunt
        uses: woffenden/github-actions/install-terragrunt@alpha
        with:
          terragrunt_version: v0.36.6

      - name: Initialise Terragrunt
        run: terragrunt init -upgrade

      - name: Terragrunt Plan
        run: terragrunt plan

      - name: Terragrunt Apply
        run: terragrunt apply -auto-approve