---
name: "composite-test"

on:
  push:
    branches:
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: woffenden/github-actions/install-terraform@alpha
        with:
          terraform_version: 1.1.7

      - name: Install Terragrunt
        uses: woffenden/github-actions/install-terragrunt@alpha
        with:
          terragrunt_version: v0.36.6

      - name: Test Terraform
        run: terraform version

      - name: Test Terragrunt
        run: terragrunt -v
