---
name: Containers

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/containers.yml
      - containers/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/containers.yml
      - containers/**

permissions: read-all

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      images: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Detect Changes
        id: detect_changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: .github/path-filters/containers.yml

  container-workflow:
    if: ${{ needs.detect-changes.outputs.images != '[]' }}
    needs: [detect-changes]
    name: Reusable Workflow
    permissions:
      contents: read
      id-token: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.images) }}
    uses: ./.github/workflows/reusable-workflow-containers.yml
    with:
      image: ${{ matrix.image }}
