---
name: Containers

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/containers.yml
      - containers/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/containers.yml
      - containers/**

permissions: read-all

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      images: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Detect changes
        id: detect_changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: .github/path-filters/containers.yml

  build:
    if: ${{ needs.detect-changes.outputs.images != '[]' }}
    needs: [detect-changes]
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.images) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Prepare Environment
        id: prepare_environment
        run: |
          echo "name=$(jq -r '.name' containers/${{ matrix.image }}/config.json)" >>"${GITHUB_ENV}"
          echo "version=$(jq -r '.version' containers/${{ matrix.image }}/config.json)" >>"${GITHUB_ENV}"

      - name: DEBUG
        id: debug
        run: |
          echo "Container Image: ${{ env.name }}"
          echo "Container Version: ${{ env.version }}"
