---
name: Dev Container

on:
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/path-filters/devcontainer.yml
      - .github/workflows/devcontainer.yml

permissions: read-all

env:
  DEVCONTAINER_CLI_VERSION: latest

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Detect Changes
        id: detect_changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: .github/path-filters/devcontainer.yml

  test:
    if: ${{ needs.detect-changes.outputs.features != '[]' }}
    needs: [detect-changes]
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        feature: ${{ fromJson(needs.detect-changes.outputs.features) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install devcontainers CLI
        id: install_devcontainers_cli
        run: npm install -g @devcontainers/cli@${{ env.DEVCONTAINER_CLI_VERSION }}

      - name: Build Test Image
        id: build_test_image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          file: .devcontainer/features/test/Containerfile
          load: true
          tags: devcontainer-test

      - name: Testing ${{ matrix.feature }}
        id: test_feature
        run: |
          devcontainer features test \
            --skip-scenarios \
            --project-folder .devcontainer/features \
            --features ${{ matrix.feature }} \
            --base-image devcontainer-test

      - name: Testing ${{ matrix.feature }} Scenarios
        id: test_feature_scenarios
        run: |
          devcontainer features test \
            --project-folder .devcontainer/features \
            --features ${{ matrix.feature }} \
            --skip-autogenerated \
            --base-image devcontainer
