---
name: Dev Container

on:
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/path-filters/devcontainer.yml
      - .github/workflows/devcontainer.yml

permissions: read-all

env:
  DEVCONTAINER_CLI_VERSION: latest

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.detect_changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Detect changes
        id: detect_changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: .github/path-filters/devcontainer.yml

  test:
    if: ${{ needs.detect-changes.outputs.features != '[]' }}
    needs: [detect-changes]
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        feature: ${{ fromJson(needs.detect-changes.outputs.features) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install devcontainers CLI
        id: install_devcontainers_cli
        run: npm install -g @devcontainers/cli@${{ env.DEVCONTAINER_CLI_VERSION }}

      - name: Build test image
        id: build_test_image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          file: .devcontainer/features/test/Containerfile
          load: true
          tags: devcontainer-test

      - name: Testing ${{ matrix.feature }}
        id: test_feature
        run: |
          devcontainer features test \
            --skip-scenarios \
            --project-folder .devcontainer/features \
            --features ${{ matrix.feature }} \
            --base-image devcontainer-test

      - name: Testing ${{ matrix.feature }} scenarios
        id: test_feature_scenarios
        run: |
          devcontainer features test \
            --project-folder .devcontainer/features \
            --features ${{ matrix.feature }} \
            --skip-autogenerated \
            --base-image devcontainer
