---
name: Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - docs/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - docs/**

concurrency:
  group: documentation

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.12

      - name: Configure Pages
        id: configure_pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0

      - name: Install Requirements
        id: install_requirements
        run: python -m pip install --requirement requirements.txt

      - name: Build Site
        id: build_site
        run: python -m mkdocs build --config-file mkdocs.yml --site-dir _site

      - name: Upload Pages Artifact
        if: github.ref == 'refs/heads/main'
        id: upload_pages_artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs/_site/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # v4.0.4
