---
name: Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - docs/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - docs/**

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: 3.11

      - name: Configure Pages
        id: configure_pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6

      - name: Install Requirements
        id: install_requirements
        run: python -m pip install --requirement requirements.txt

      - name: Build Site
        id: build_site
        run: python -m mkdocs build --config-file mkdocs.yml --site-dir _site

      - name: Upload Pages Artifact
        id: upload_pages_artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
