---
name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run Analysis
        id: run_analysis
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        id: upload_sarif_results
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v3.1.0
        with:
          name: SARIF Results
          path: results.sarif
          retention-days: 5

      - name: Upload to CodeQL
        id: upload_to_codeql
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
        with:
          sarif_file: results.sarif
