---
name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Analysis
        id: run_analysis
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        id: upload_sarif_results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF Results
          path: results.sarif
          retention-days: 5

      - name: Upload to CodeQL
        id: upload_to_codeql
        uses: github/codeql-action/upload-sarif@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.30.0
        with:
          sarif_file: results.sarif
