---
name: Super-Linter

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Load Super-Linter Variables
        id: load_super_linter_variables
        run: cat .github/super-linter.env >>"${GITHUB_ENV}"

      - name: Super-Linter
        id: super_linter
        uses: super-linter/super-linter/slim@962a6409c1b303d0e53a9d34ada577a0362f4fae # v5.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
