---
name: Super-Linter

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0

      - name: Load Super-Linter Variables
        id: load_super_linter_variables
        run: cat .github/super-linter.env >>"${GITHUB_ENV}"

      - name: Super-Linter
        id: super_linter
        uses: super-linter/super-linter/slim@b944539b2df01cb8d17504d2fd9411d354e8078a # v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
