---
name: Pull request assigner

on:
  pull_request:
    types:
      - opened
      - reopened

permissions: read-all

jobs:
  pull-request-assigner:
    name: Pull request assigner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Pull request assigner
        id: pull_request_assigner
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            })
