---
name: Dependabot Configuration Generator

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/.terraform.lock.hcl"

permissions: read-all

jobs:
  dependabot-configuration-generator:
    name: Dependabot Configuration Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run Dependabot Configuration Generator
        id: run_dependabot_configuration_generator
        run: bash -x scripts/dependabot/configuration-generator.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
