---
name: Terraform - AWS - Root

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-aws-root.yml
      - terraform/aws/accounts/root/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-aws-root.yml
      - terraform/aws/accounts/root/**

permissions: read-all

jobs:
  organisation:
    name: Organisation
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/aws/accounts/root/organisation
      cloud-provider: aws
      aws-region: eu-west-2
      aws-role-to-assume: arn:aws:iam::749019155605:role/github-actions

  iam:
    name: IAM
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/aws/accounts/root/iam
      cloud-provider: aws
      aws-region: eu-west-2
      aws-role-to-assume: arn:aws:iam::749019155605:role/github-actions

  sso:
    needs: [organisation]
    name: SSO
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/aws/accounts/root/sso
      cloud-provider: aws
      aws-region: eu-west-2
      aws-role-to-assume: arn:aws:iam::749019155605:role/github-actions

  route53:
    name: Route 53
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      working-directory: terraform/aws/accounts/root/route53
      cloud-provider: aws
      aws-region: eu-west-2
      aws-role-to-assume: arn:aws:iam::749019155605:role/github-actions
