---
  name: Terraform - Google
  
  on:
    pull_request:
      branches:
        - main
      paths:
        - .github/workflows/terraform-google.yml
        - terraform/google/**
    push:
      branches:
        - main
      paths:
        - .github/workflows/terraform-google.yml
        - terraform/google/**
    
  permissions: read-all
  
  jobs:
    mta-sts:
      name: MTA-STS
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: terraform/google/mta-sts
      permissions:
        contents: read
        id-token: write
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
  
        - name: Configure Google Credentials
          id: configure_google_credentials
          uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
          with:
            workload_identity_provider: principalSet://iam.googleapis.com/projects/800000204119/locations/global/workloadIdentityPools/github-actions/providers/github-actions
            service_account: github-actions@woffenden.iam.gserviceaccount.com
