---
name: Cloudflare WARP
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cloudflare WARP
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: ${{ secrets.CLOUDFLARE_ZT_ORG }}
          auth_client_id: ${{ secrets.CLOUDFLARE_ZT_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_ZT_CLIENT_SECRET }}

      - name: Test
        run: |
          warp-cli debug network
          curl -s https://www.cloudflare.com/cdn-cgi/trace
